FROM python:3.12-alpine
RUN mkdir -p /data && dd if=/dev/zero of=/data/bigfile bs=1M count=2048 
RUN apk add --no-cache busybox-static
RUN mkdir -p /www && echo "Large image test - Index" > /www/index.html && chown -R 1000:1000 /www
EXPOSE 8080
RUN adduser -D -u 1000 appuser
USER appuser
CMD ["python", "-m", "http.server", "8080", "--directory", "/www"]