---
- name: Install dnsmasq
  package:
    name: dnsmasq
    state: present

- name: Deploy dnsmasq configuration
  template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart dnsmasq

- name: Enable and start dnsmasq
  service:
    name: dnsmasq
    state: started
    enabled: true
