- name: Create lab users
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    create_home: yes
    state: present
    system: true
  loop:
    - { name: 'ocpsa', groups: 'libvirt' }
    - { name: 'rhelsa', groups: 'libvirt' }
    - { name: 'cback', groups: 'wheel, libvirt' }

- name: Set ACLs for qemu and root on home dirs
  ansible.posix.acl:
    path: "/home/{{ item }}"
    entity: "{{ acl_user }}"
    etype: user
    permissions: rwx
    state: present
  loop: "{{ ['cback', 'rhelsa', 'ocpsa'] | product(['qemu', 'root']) | list }}"
  loop_control:
    loop_var: pair
  vars:
    item: "{{ pair.0 }}"
    acl_user: "{{ pair.1 }}"

- name: Set ACL for cback on /home/ocpsa
  ansible.posix.acl:
    path: /home/ocpsa
    entity: cback
    etype: user
    permissions: rwx
    state: present
