# Installs a RHEL 9.4 lab on a RHEL 9.4 libvirt host
- name: Setup the RHEL 9.4 Lab VM
  hosts: all
  become: yes
  vars:
    vm_name: "cback-rhel94-lab"
    memory_gb: 16
    cpu_number: 8
    rhel_pool_name: "rhel-lab-pool-1"
    rhel_net_name: "rhel-netpool-1"
    iso_path: "/home/rhelsa/images/rhel94-lab.qcow2"
    rhel_pool_path: "/home/rhelsa/{{ rhel_pool_name }}"
    disk_size: "40G"
    disk_image_path: "/home/rhelsa/{{ rhel_pool_name }}/{{ vm_name }}-vm.qcow2"
    bridge_name: "virbr1"

  tasks:
    - name: Check connection to server
      ansible.builtin.ping:

    - name: Logging for ping success
      ansible.builtin.debug:
        msg: "Ping successful. RHEL94 server can be reached. Proceeding with installation"

    - name: Ensure storage pool is defined
      community.libvirt.virt_pool:
        command: define
        name: "{{ rhel_pool_name }}"
        xml: "{{ lookup('template', '../templates/template-rhelstoragepool-1.xml.j2') }}"
      ignore_errors: yes

    - name: Start and activate storage pool
      community.libvirt.virt_pool:
        state: active
        name: "{{ rhel_pool_name }}"

    - name: Ensure storage pool is persistent
      community.libvirt.virt_pool:
        state: present
        name: "{{ rhel_pool_name }}"

    - name: Start and activate network pool
      community.libvirt.virt_net:
        state: active
        name: "{{ rhel_net_name }}"

    - name: Ensure network pool is persistent
      community.libvirt.virt_net:
        state: present
        name: "{{ rhel_net_name }}"

    - name: Check if disk image exists
      ansible.builtin.stat:
        path: "{{ disk_image_path }}"
      register: img_stat

    - name: Create disk image if it does not exist
      ansible.builtin.command:
        cmd: "qemu-img create -f qcow2 '{{ disk_image_path }}' {{ disk_size }}"
      when: not img_stat.stat.exists

    - name: Define the RHEL 9.4 VM
      community.libvirt.virt:
        name: "{{ vm_name }}"
        command: define
        xml: "{{ lookup('template', '../templates/template-rhel-94.xml.j2') }}"

    - name: Autostart VM on host boot
      community.libvirt.virt:
        name: "{{ vm_name }}"
        autostart: true

    - name: Start the VM
      community.libvirt.virt:
        name: "{{ vm_name }}"
        state: running

    - name: Log installation success
      ansible.builtin.debug:
        msg: "RHEL 9.4 VM installation successful!"
