# ansible-playbook -i "hostip," --user=user --ask-become-password playbook 
- name: Setup the main lab environment - hypervisor
  hosts: all
  become: yes
  tasks: 

    - name: Check connection to workstation
      ping: 
      register: ping_re
      ignore_errors: yes

    - name: Fail if no connection
      fail:
        msg: "No connection to workstation."
      when: ping_re.failed

    - name: Update system
      dnf:
        name: '*'
        state: latest
      when: not ping_re.failed 
    
    - name: Logging for ping success
      debug: 
        msg: "Ping successful. RHEL94 server can be reached. Proceeding with installation"
      when: not ping_re.failed 

    - name: Install packages for development
      dnf: 
        name: "{{ item  }}"
        state: present
      loop:
        - bash-completion
        - git
        - vim
        - python3
        - python3-pip
        - podman
        - wget
        - qemu-kvm
        - libvirt
        - virt-install
        - virt-viewer
      when: not ping_re.failed 

    - name: Enable virtualization services
      ansible.builtin.service:
        name: "virt{{ item[0] }}d{{ item[1] | default('') }}.socket"
        state: started
        enabled: yes
      loop:
        - [ "qemu", "" ]
        - [ "qemu", "-ro" ]
        - [ "qemu", "-admin" ]
        - [ "network", "" ]
        - [ "network", "-ro" ]
        - [ "network", "-admin" ]
        - [ "nodedev", "" ]
        - [ "nodedev", "-ro" ]
        - [ "nodedev", "-admin" ]
        - [ "nwfilter", "" ]
        - [ "nwfilter", "-ro" ]
        - [ "nwfilter", "-admin" ]
        - [ "secret", "" ]
        - [ "secret", "-ro" ]
        - [ "secret", "-admin" ]
        - [ "storage", "" ]
        - [ "storage", "-ro" ]
        - [ "storage", "-admin" ]
        - [ "interface", "" ]
        - [ "interface", "-ro" ]
        - [ "interface", "-admin" ]

    - name: Validate virtualization 
      ansible.builtin.command: virt-host-validate
      register: validation_output
      changed_when: false

    - name: KVM VZ Results
      ansible.builtin.debug:
        msg: "{{ validation_output.stdout_lines }}"

    - name: Log installation
      debug: 
        msg: "Installation successful"
      when: not ping_re.failed