- name: Setup the main lab environment - hypervisor
  hosts: all
  become: yes
  vars:
    vm_name: "cback-rhel94-lab"
    memory_gb: 16
    cpu_number: 8
    storagepool_name: "rhel-lab-pool-1"
    netpool_name: "rhel-netpool-1"
    iso_path: "/home/rhelsa/images/rhel94-lab.qcow2"
    disk_image_path: "/home/rhelsa/{{ storagepool_name }}/{{ vm_name }}-vm.qcow2"

  tasks:
    - name: Check connection
      ping:

    - name: Create storage pool if missing
      shell: |
        virsh pool-define-as --name {{ storagepool_name }} --type dir --target /home/rhelsa/{{ storagepool_name }}
        virsh pool-start {{ storagepool_name }}
        virsh pool-autostart {{ storagepool_name }}
      args:
        executable: /bin/bash
      when: "'{{ storagepool_name }}' not in lookup('pipe', 'virsh pool-list --all')"

    - name: Create disk image if missing
      command: qemu-img create -f qcow2 "{{ disk_image_path }}" 40G
      args:
        creates: "{{ disk_image_path }}"

    - name: Define the RHEL LAB VM
      community.libvirt.virt:
        name: "{{ vm_name }}"
        xml: "{{ lookup('template', '../templates/template-rhel-94.xml.j2') }}"
        command: define
        autostart: true

    - name: Start VM
      command: virsh start "{{ vm_name }}"

    - name: Enable serial console
      command: |
        virsh console {{ vm_name }} --force
      ignore_errors: yes
