# Installs a RHEL 9.4 lab on a RHEL 9.4 libvirt host

- name: Setup the main lab environment - hypervisor
  hosts: all
  become: yes
  vars:
    vm_name: "cback-rhel94-lab"
    memory_gb: 16
    cpu_number: 8
    storagepool_name: "rhel-lab-pool-1"
    netpool_name: "rhel-netpool-1"
    iso_path: "/home/rhelsa/"

  tasks: 
    - name: Check connection to server
      ping: 
      register: ping_re
      ignore_errors: yes

    - name: Fail if no connection
      fail:
        msg: "No connection to workstation."
      when: ping_re.failed
    
    - name: Logging for ping success
      debug: 
        msg: "Ping successful. RHEL94 server can be reached. Proceeding with installation"
      when: not ping_re.failed 

    - name: Define the RHEL LAB vm
      community.libvirt.libvirt_domain:
        name: "{{ vm_name }}"
        state: "defined"
        xml: "{{ lookup('template', 'template-rhel-94.xml.j2') }}"