# Setup the main lab environment - hypervisor
- name: Setup the main lab environment - hypervisor
  hosts: all
  become: yes
  vars:
    ocp_pool_name: "ocp-pool-1"
    ocp_pool_path: "/home/ocpsa/ocp-pool-1"
    rhel_pool_name: "rhel-lab-pool-1"
    rhel_pool_path: "/home/rhelsa/rhel-lab-pool-1"

    ocp_net_name: "ocp-netpool-1"
    ocp_bridge: "virbr1"
    ocp_ip: "192.168.10.20"
    ocp_range_start: "192.168.10.21"
    ocp_range_end: "192.168.10.100"

    rhel_net_name: "rhel-netpool-1"
    rhel_bridge: "virbr2"
    rhel_ip: "192.168.11.20"
    rhel_range_start: "192.168.11.21"
    rhel_range_end: "192.168.11.100"

  tasks:
    - name: Check connection to server
      ping:

    - name: Update system
      dnf:
        name: '*'
        state: latest

    - name: Install required packages
      dnf:
        name:
          - bash-completion
          - git
          - vim
          - python3
          - python3-pip
          - podman
          - wget
          - qemu-kvm
          - libvirt
          - virt-install
          - virt-viewer
          - osbuild-composer
          - composer-cli
          - cockpit-composer
        state: present

    - name: Enable RHEL Image composer-cli
      ansible.builtin.service:
        name: osbuild-composer 
        state: started
        enabled: yes

    - name: Enable RHEL Image cockpit
      ansible.builtin.service:
        name: cockpit 
        state: started
        enabled: yes


    - name: Enable virtualization services
      ansible.builtin.service:
        name: "virt{{ item[0] }}d{{ item[1] | default('') }}.socket"
        state: started
        enabled: yes
      loop:
        - [ "qemu", "" ]
        - [ "network", "" ]
        - [ "nodedev", "" ]
        - [ "nwfilter", "" ]
        - [ "secret", "" ]
        - [ "storage", "" ]
        - [ "interface", "" ]

    - name: Validate virtualization
      command: virt-host-validate
      register: validation_output
      changed_when: false

    - name: KVM VZ Results
      debug:
        msg: "{{ validation_output.stdout_lines }}"

    - name: Create system user ocpsa for OpenShift labs
      user:
        name: ocpsa
        create_home: yes
        state: present
        system: true

    - name: Create system user rhelsa for RHEL labs
      user:
        name: rhelsa
        create_home: yes
        state: present
        system: true

    - name: Define and start OpenShift storage pool
      community.libvirt.virt_pool:
        command: define
        name: "{{ ocp_pool_name }}"
        xml: "{{ lookup('template', '../templates/template-ocpstoragepool-1.xml.j2') }}"
      vars:
        pool_name: "{{ ocp_pool_name }}"
        pool_path: "{{ ocp_pool_path }}"

    - name: Start and activate OpenShift storage pool
      community.libvirt.virt_pool:
        state: active
        name: "{{ ocp_pool_name }}"

    - name: Define and start RHEL LAB storage pool
      community.libvirt.virt_pool:
        command: define
        name: "{{ rhel_pool_name }}"
        xml: "{{ lookup('template', '../templates/template-rhelstoragepool-1.xml.j2') }}"
      vars:
        pool_name: "{{ rhel_pool_name }}"
        pool_path: "{{ rhel_pool_path }}"

    - name: Start and activate RHEL LAB storage pool
      community.libvirt.virt_pool:
        state: active
        name: "{{ rhel_pool_name }}"

    - name: Define OpenShift network pool
      community.libvirt.virt_net:
        command: define
        name: "{{ ocp_net_name }}"
        xml: "{{ lookup('template', '../templates/template-ocpnetpool-1.xml.j2') }}"
      vars:
        pool_name: "{{ ocp_net_name }}"
        bridge_name: "{{ ocp_bridge }}"
        ip_address: "{{ ocp_ip }}"
        range_start: "{{ ocp_range_start }}"
        range_end: "{{ ocp_range_end }}"

    - name: Define RHEL LAB network pool
      community.libvirt.virt_net:
        command: define
        name: "{{ rhel_net_name }}"
        xml: "{{ lookup('template', '../templates/template-rhelnetpool-1.xml.j2') }}"
      vars:
        pool_name: "{{ rhel_net_name }}"
        bridge_name: "{{ rhel_bridge }}"
        ip_address: "{{ rhel_ip }}"
        range_start: "{{ rhel_range_start }}"
        range_end: "{{ rhel_range_end }}"

    - name: Start and activate OpenShift network
      community.libvirt.virt_net:
        state: active
        name: "{{ ocp_net_name }}"

    - name: Start and activate RHEL LAB network
      community.libvirt.virt_net:
        state: active
        name: "{{ rhel_net_name }}"

    - name: Set ACLs for qemu user on ISO and storage directories
      command: setfacl -m u:qemu:x /home/cback
      ignore_errors: yes

    - name: Set ACLs for qemu user on RHEL LAB storage directory
      command: setfacl -m u:qemu:x /home/rhelsa/rhel-lab-pool-1
      ignore_errors: yes

    - name: Set ACLs for qemu user on storage pool disk file
      command: setfacl -m u:qemu:r /home/rhelsa/rhel-lab-pool-1/cback-rhel94-lab-vm.qcow2
      ignore_errors: yes

    - name: Log installation success
      debug:
        msg: "Hypervisor setup complete!"