name = "rhel94-lab"
description = "RHEL 9.4 image for easy lab use."
version = "1.0.0"

[[packages]]
name = "selinux-policy-targeted"
version = "*"

[[packages]]
name = "policycoreutils"
version = "*"

[[packages]]
name = "cloud-init"
version = "*"

[[packages]]
name = "qemu-guest-agent"
version = "*"

[[packages]]
name = "bash"
version = "*"

[[packages]]
name = "vim"
version = "*"

[[packages]]
name = "wget"
version = "*"

[[packages]]
name = "firewalld"
version = "*"

[customizations]
hostname = "rhel94-lab"

[[customizations.user]]
name = "admin"
password = "admin"
groups = ["wheel"]
home = "/home/admin"
shell = "/bin/bash"

[customizations.firewall]
ports = ["22:tcp", "80:tcp"]

[customizations.services]
enabled = ["sshd", "qemu-guest-agent", "cloud-init"]

[customizations.selinux]
enabled = true
state = "enforcing"

[customizations.kernel]
append = "console=ttyS0 console=ttyS1,115200n8"

[image]
name = "rhel94-lab"
distribution = "rhel-94"
format = "qcow2"
size = 21474836480
